# .github/workflows/ci.yml
name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest # Use Linux runner
    strategy:
      matrix:
        python-version: ["3.10", "3.11"] # Test against multiple Python versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Add any OS-specific dependencies here if needed, e.g., for MuJoCo/rendering on Linux
        # sudo apt-get update && sudo apt-get install -y <packages>

    - name: Lint with Ruff
      run: |
        pip install ruff # Ensure ruff is installed
        ruff check . # Check for lint errors
        ruff format --check . # Check formatting
      # Optionally fail the job if linting issues are found:
      # continue-on-error: false 

    - name: Test with Pytest
      run: |
        pip install pytest # Ensure pytest is installed
        pytest 